In [1]:
!pip3.9 install --upgrade pip
!pip3.9 install pandas

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.2.4)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pandas in /usr/local/lib/python3.9/site-packages (1.3.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/site-packages (from pandas) (1.21.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/site-packages (from pandas) (2021.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [2]:
import pandas as pd
from datetime import datetime

In [3]:
# 파일 불러오기
import glob

path = r'./data' # use your path
all_files = glob.glob(path + "/210901/13*.csv")

count = len(all_files)
print("Reading", count, "Files")

li = []

for i, filename in enumerate(all_files):
    df = pd.read_csv(filename, index_col=None, header=0)
    
    filedatelist = filename.split("/")
    filedate = filedatelist[2] + filedatelist[3][:-4]
#     print(datetime.strptime(filedate, "%y%m%d%H%M%S"))
#     print(filedate)
    
    df["time"] = datetime.strptime(filedate, "%y%m%d%H%M%S")
    
    li.append(df)
    
    if (i + 1) % 100 == 0:
        print(f"Read {i + 1}/{count}")

print("Read Complete")

df = pd.concat(li, axis=0, ignore_index=True)
print("Concat Complete")

Reading 60 Files
Read Complete
Concat Complete

In [4]:
df

,vehicleno,lati,long,nodeid,nodenm,vehicleno.1,time
0,1382,35.951980,129.407671,PHB350099143,신문덕코아루,1382,2021-09-01 13:07:03
1,1261,35.987233,129.362261,PHB350098010,장흥동사거리,1261,2021-09-01 13:07:03
2,1343,36.019281,129.361965,PHB350093007,상대시장,1343,2021-09-01 13:07:03
3,1239,36.040211,129.366455,PHB351008001,육거리,1239,2021-09-01 13:07:03
4,1428,36.063368,129.381268,PHB351015013,동부초등학교후문,1428,2021-09-01 13:07:03
...,...,...,...,...,...,...,...
748,1377,36.068675,129.391808,PHB351017002,환호해맞이그린빌,1377,2021-09-01 13:36:03
749,1346,36.047693,129.365080,PHB351009012,건강가정다문화센터,1346,2021-09-01 13:36:03
750,1348,36.016888,129.360008,PHB350092014,KT(세명기독병원),1348,2021-09-01 13:36:03
751,1349,35.995640,129.352333,PHB350086024,영일고등학교,1349,2021-09-01 13:36:03
752,1229,35.972221,129.384361,PHB350098016,성우오토모티브,1229,2021-09-01 13:36:03

In [5]:
df.sort_values("time")

,vehicleno,lati,long,nodeid,nodenm,vehicleno.1,time
267,1431,35.951998,129.407578,PHB350099142,신문덕코아루,1431,2021-09-01 13:00:04
258,1239,36.027440,129.367355,PHB350094011,고속버스터미널,1239,2021-09-01 13:00:04
259,1428,36.068018,129.372181,PHB351016001,장성초등학교,1428,2021-09-01 13:00:04
260,1338,36.074075,129.397875,PHB351017008,청소년수련관,1338,2021-09-01 13:00:04
261,1377,36.102991,129.402068,PHB350099302,에코프로EM,1377,2021-09-01 13:00:04
...,...,...,...,...,...,...,...
91,1431,35.959433,129.408648,PHB350099147,문덕초등학교,1431,2021-09-01 13:59:02
102,1349,35.940133,129.389841,PHB350087168,문덕차고지,1349,2021-09-01 13:59:02
103,1229,35.940145,129.389818,PHB350087168,문덕차고지,1229,2021-09-01 13:59:02
98,1338,36.068751,129.372214,PHB351014009,장성초등학교,1338,2021-09-01 13:59:02
96,1343,36.096368,129.404582,PHB350099307,우전지앤에프,1343,2021-09-01 13:59:02

In [7]:
df.shape

(753, 7)